name: tensorflow
description: Native bindings for Tensorflow.
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
publish_to: none
dependencies:
  binary: ^0.1.3
  build_config: ^0.2.0
  fixnum: ^0.10.7
  protobuf: ^0.7.2
  source_gen: ^0.8.0
  symbol_table: ^1.0.0
  tuple: ^1.0.0
dev_dependencies:
  build_runner: ^0.8.0
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  recase: ^1.0.0
  system_info: ^0.0.16
  test: ^0.12.0
  vector_math: ^2.0.0