name: tensorflow
description: Native bindings for Tensorflow. Includes functionality for importing graphs, and constructing them at low and high levels.
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/tensorflow.dart
environment:
  sdk: ">=2.0.0-dev <3.0.0"
dependencies:
  binary: ^0.1.3
  collection: ^1.0.0
  fixnum: ^0.10.7
  meta: ^1.0.0
  path: ^1.0.0
  protobuf: ^0.7.2
  symbol_table: ^1.0.0
  tuple: ^1.0.0
dev_dependencies:
  args: ^1.0.0
  cli_util: ^0.1.3
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  recase: ^1.0.0
  system_info: ^0.0.16
  test: ^0.12.0
  vector_math: ^2.0.0
scripts:
  build: dart tool/build.dart
  get: dart tool/build.dart